version: '3.8'
services:
  web:
    image: 992151247814.dkr.ecr.us-west-1.amazonaws.com/pavandas/flask-app:latest
    ports:
      - "5000:5000"
    depends_on: 
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
 redis:
   image: redis:alpine
   ports: 
     - "6379:6379"
   deploy:
     replicas: 2
