---
 # - name: Install AWS CLI
 #   apt: 
 #    name: awscli
 #    state: present
 #    update_cache: true
 #   tags: login



 # - name: Login to AWS  ecr
 #   shell: |
 #     aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 992151247814.dkr.ecr.us-west-1.amazonaws.com
 #   args: 
 #     executable: /bin/bash
 #   tags: login


 - name: Pull custom app image from ECR
   shell: docker pull 992151247814.dkr.ecr.us-west-1.amazonaws.com/pavandas/flask-app:latest
   tags: deploy

 - name: Deploy stack
   copy:
     src: ../../docker/docker-compose.yml
     dest: /tmp/docker-compose.yml
   tags: deploy


 - name: Deploy services using docker stack
   shell: docker stack deploy -c /tmp/docker-compose.yml mystack
   tags: deploy
...
