---
 - name: Check if node is already part of a swarm
   shell: docker info --format '{{ .Swarm.LocalNodeState }}'
   register: swarm_status

 - name: Initialize docker swarm if not already initialized
   shell: docker swarm init --advertise-addr {{ ansible_host }}
   when: swarm_status.stdout != 'active'
   register: swarm_init_result
   
 - name: Get worker join token
   shell: docker swarm join-token worker -q
   register: worker_token
   # when: swarm_init_result is succeeded
   ignore_errors: true

 - name: save token
   set_fact:
     join_token: "{{worker_token.stdout}}"
   # when: swarm_init_result is succeeded and worker_token is defined and worker_token.stdout is defined
...

